### ISSUE TITLE
Invalid PHPDoc blocks

### ISSUE THREAD

**Issue by szepeviktor** [paulthewalton/acf-pro-stubs#1]
Static analysis is much less useful with invalid PHPDocs

e.g. `@param	$post_id (int)`

See the fix here
https://github.com/szepeviktor/phpstan-wordpress/blob/master/stub-generators/acf-pro-generate-stubs.sh#L8-L22

**Comment by paulthewalton** [comment]
Fixed in [b1e1f73](https://github.com/paulthewalton/acf-pro-stubs/commit/b1e1f735dd75569822eb44436e42f5e2418f47e7)

**Comment by szepeviktor** [comment]
Thank you.
